version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.13@sha256:991bcf4d64fb0038ba55dc0660f9ecd2dc4482bcdf5197fa99df360e28b9fe3e
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

            - v1-dependencies-

      - run:
          name: "Npm Install"
          command: make install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Run tests"
          command: npm run test

      - run:
          name: "Deploy Hosting"
          command: make deploy
